version: "3.8"

services:

  service1:
    container_name: boilerplate
    build: .
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    restart: always
